[build-system]
requires = ["maturin>=1"]
build-backend = "maturin"

[project]
name = "staff-cli"
description = "A toolkit for LLM."
requires-python = ">=3.7"

[tool.maturin]
bindings = "bin"
strip = true
