[build-system]
requires = ["maturin>=1"]
build-backend = "maturin"

[project]
name = "staff-cli"
version = "0.1.1"
description = "A toolkit for LLM."

[tool.maturin]
bindings = "bin"
manifest-path = "crates/cli/Cargo.toml"
strip = true
